CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- auto-incrementing field
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    image VARCHAR(255),
    category VARCHAR(255),
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    internal_reference VARCHAR(255),
    shell_id INT NOT NULL,
    inventory_status VARCHAR(255) NOT NULL,  -- Keeping it as VARCHAR
    rating INT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-incrementing ID
    username VARCHAR(20) NOT NULL,  -- Username field with a maximum length of 20 characters
    email VARCHAR(50) NOT NULL UNIQUE,  -- Email field with a maximum length of 50 characters, ensuring uniqueness
    password VARCHAR(120) NOT NULL,  -- Password field with a maximum length of 120 characters
    CONSTRAINT unique_username UNIQUE (username)  -- Ensure the username is unique
);

